[package]
name = "errand"
version = "0.1.0"
edition = "2024"

[dependencies]
jsonc-parser = { version = "0.33.2", features = ["serde"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = { version = "1.0.151", features = ["preserve_order"] }

[lints.rust]
unsafe_code = "forbid"
warnings = "deny"

[lints.clippy]
pedantic = "deny"
